# The Website Basic Settings
title: BeingArcade
header:  Arcade Of Being
desc: > 
 Fear not, the dark, my friend.
 And let the feast begin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

post_title: Event
post_date: TimeScale
post_cat: Record

prev-next: true
favicon: "/assets/icon.png"
paginate: 15
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji



# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
